name: CI/CD Pipeline

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install depedencies
        uses: npm install --legacy-peer-deps
      
      - name: Run tests
        uses: npm run test
      